### ISSUE TITLE
Syntax error in Windows

### ISSUE THREAD

**Issue by young** [BohdanTkachenko/webpack-split-by-path#1]
`SyntaxError: Invalid regular expression: /^G:\Dev\node_modules\/: \ at end of pattern`

Windows uses "\" as a path delimiter so any path ending in a slash will raise a syntax error from the regular expression `return new RegExp('^' + path);`.

**Comment by BohdanTkachenko** [comment]
Should work now. Please re-open bug if problem still occurs.

**Comment by young** [comment]
That fixed it. Thanks!
