### ISSUE TITLE
Does not work in windows

### ISSUE THREAD

**Issue by zivni** [BohdanTkachenko/webpack-split-by-path#12]
The problem is that windows paths start with a drive letter.
You are escaping the path in the function regExpQuote(str), but i think it escapes too much.
When I changed according to http://stackoverflow.com/a/6969486/1353412 to

```
function regExpQuote(str) {
  return (str + '').replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, '\\$&');
}
```

it worked well.

**Comment by BohdanTkachenko** [comment]
I have no Windows environment. Could you please change this regular expression and make PR to this repo?
