### ISSUE TITLE
Does not play nice with CompressionPlugin

### ISSUE THREAD

**Issue by aldendaniels** [BohdanTkachenko/webpack-split-by-path#15]
If I use both `SplitByPathPlugin` to break  out a `vendor.js` and `CompressionPlugin` to compress the resulting bundles, then only the `vendor.js` bundle is compressed. The primary (`index.js`) bundle is not compressed.

**Comment by BohdanTkachenko** [comment]
Hi @aldendaniels 

We just released 2.0.0 version of this plugin for webpack 2. 
For webpack 1 there is still a branch webpack1 and version 1.0.0 on NPM.

Please consider upgrading to webpack 2 and version 2.0.0 of this plugin.
If this issue still reproduces on 2.0.0 please re-open this issue.
If you really need to have this in 1.0.0, PR's to webpack1 branch are always welcome, but I don't longer plan to fix issues for webpack1.

Thanks!
