### ISSUE TITLE
chunk order Not work well with html-webpack-plugin

### ISSUE THREAD

**Issue by e-cloud** [BohdanTkachenko/webpack-split-by-path#18]
now the generated output is good, but when using with `html-webpack-plugin`, in my case, the generated script tag order is not what expected.

i.e. one possible result for now.

```
...
<script type="text/javascript" src="manifest_ed6c67841e.js"></script>
<script type="text/javascript" src="main_4c9ecd6b3d.js"></script>
<script type="text/javascript" src="vendor_265cd3b016.js"></script>
...
```

the expected result

```
<script type="text/javascript" src="manifest_ed6c67841e.js"></script>
<script type="text/javascript" src="vendor_265cd3b016.js"></script>
<script type="text/javascript" src="main_4c9ecd6b3d.js"></script>
```

i think this result is caused by the chunk order or priority.
As the manifest chunk is the entry chunk, of course i will have highest priority.
But the others' order is sorted by webpack. So, We should level up the extracted chunks priority.

However, i can't find a solution according to the webpack document.
Therefore I need someone's help.

@sokra, @bebraw, could you guys give some expertise?

**Comment by bebraw** [comment]
What does your html-webpack-plugin configuration look like? Which `chunksSortMode` are you using? Have you tried out different options for that?

**Comment by e-cloud** [comment]
@bebraw , i'm a fool. I didn't keep update with html-webpack-plugin for such a while. So, i did not notice there provides a `chunksSortMode` option.

As i tried the `dependency` value, things work as wanted.

Thank you for your guidance.

**Comment by bebraw** [comment]
No problem. Great to hear you got it to work. 👍
