### ISSUE TITLE
0.1.0 Breaks in Webpack Dev Server

### ISSUE THREAD

**Issue by jsg2021** [BohdanTkachenko/webpack-split-by-path#21]
Haven't been able to nail down exactly what's wrong, but after first compile, if i change a source file, and refresh the app, there is an error in the manifest. 
![screen shot 2016-07-25 at 6 03 20 pm](https://cloud.githubusercontent.com/assets/577453/17120471/2436adc6-5292-11e6-95ab-b4c05873bf9c.png)

v0.0.10 does not exhibit the problem, so I'm pinned to that for now.

**Comment by BohdanTkachenko** [comment]
Hi @jsg2021  

We just released 2.0.0 version of this plugin for webpack 2. 
For webpack 1 there is still a branch webpack1 and version 1.0.0 on NPM.
Please consider upgrading to webpack 2 and version 2.0.0 of this plugin.
If this issue still reproduces on 2.0.0 please re-open this issue.
If you really need to have this in 1.0.0, PR's to webpack1 branch are always welcome, but I don't longer plan to fix issues for webpack1.

Thanks!
