### ISSUE TITLE
The chunkFilename doesn't actually do what's expected

### ISSUE THREAD

**Issue by codingmatty** [BohdanTkachenko/webpack-split-by-path#26]
I am using the v0.10 of this plugin with Webpack v1.13 and the plugin is using the filename pattern, instead of the chunkFilename pattern.
I am not sure if that is intended, or unexpected side effect of the way this plugin is configured...

**Comment by BohdanTkachenko** [comment]
Hi @mattjdev 

We just released 2.0.0 version of this plugin for webpack 2. 
For webpack 1 there is still a branch webpack1 and version 1.0.0 on NPM.
Please consider upgrading to webpack 2 and version 2.0.0 of this plugin.
If this issue still reproduces on 2.0.0 please re-open this issue.
If you really need to have this in 1.0.0, PR's to webpack1 branch are always welcome, but I don't longer plan to fix issues for webpack1.

Thanks!
