### ISSUE TITLE
Split by path and split by name at the same time

### ISSUE THREAD

**Issue by marekpw** [BohdanTkachenko/webpack-split-by-path#3]
I'm running a configuration where the Split by path plugin splits my vendors:

```
new SplitByPathPlugin([
    {
        name: 'vendor',
        path: [
            path.join(__dirname, 'bower_components'),
            path.join(__dirname, 'node_modules')
        ]
    }
])
```

and the SplitByName plugin splits my views:

```
new SplitByNamePlugin({
    buckets: [
        {
            name: 'views',
            regex: /\.html/
        }
    ]
})
```

While this works, only the first one in the order does anything (if views get compiled first, vendors aren't and vice versa based on the order of plugins). Is there a way to make these two work together, or can you think of a way that would allow me to use only SplitByPath for both my views and my vendors?

Views are located under the app/src/any-component/_resources/views. There are numerous components.

Also let me thank you for this great plugin, it's a life saver as it finally got me somewhere. Any help is appreciated.

**Comment by BohdanTkachenko** [comment]
Hi @idiotstrike, sorry for late response. What I'm thinking is that I can implement functionality from SplitByNamePlugin in this plugin. So in result you will be able to do something like this:

```
new SplitByPathPlugin([
  {
    name: 'vendor',
    path: [
      path.join(__dirname, 'bower_components'),
      path.join(__dirname, 'node_modules')
    ]
  },
  {
    name: 'views',
    path: /\.html/
  }
])
]
```

What do you think about this?

**Comment by marekpw** [comment]
Awesome, this does help a lot. Thanks!

**Comment by BohdanTkachenko** [comment]
@idiotstrike Just pushed version 0.0.6. Please make sure that you're using it.
