### ISSUE TITLE
Doesn't work well with html-webpack-plugin

### ISSUE THREAD

**Issue by sheerun** [BohdanTkachenko/webpack-split-by-path#8]
If I use your default example with html-webpack-plugin (you can use code on https://github.com/sheerun/webpack-split), then only vendor script is included..

This plugin seems to work well with common chunks plugin.

Also see: https://github.com/ampedandwired/html-webpack-plugin/issues/127

**Comment by GreenGremlin** [comment]
Adding css-loader to the ignore option fixed this, for me.

``` JavaScript
    new SplitByPathPlugin(
      [{ name: 'vendor', path: __dirname + '/node_modules' }],
      { ignore: [__dirname + '/node_modules/css-loader'] }
    ),
```

**Comment by GreenGremlin** [comment]
I've also added style-loader and css to the ignore list.

``` javascript
ignore: [
  __dirname + '/node_modules/css-loader',
  __dirname + '/node_modules/style-loader',
  /\.css/
]
```

**Comment by e-cloud** [comment]
@GreenGremlin, to a certain extent , it works.

**Comment by BohdanTkachenko** [comment]
Is this issue still occurs? After PR #17 everything seems to work perfect with html-webpack-plugin. Please re-open this issue if you still have problems.
